import { DEFAULT_COACH_ID, createOgrenciId, createStudentCode } from "@/lib/students/constants";
import type { StudentRecord } from "@/lib/students/types";

export const SEED_STUDENTS: StudentRecord[] = [
  {
    ogrenciId: createOgrenciId(),
    coachId: DEFAULT_COACH_ID,
    name: "Ayşe Yılmaz",
    studentCode: "ÖĞ-AY001",
    sinifBranch: "12-A",
    alan: "sayisal",
    goal: "Sabancı Üniversitesi — Yönetim Bilişim Sistemleri",
    targetUniversity: "Sabancı Üniversitesi",
    targetDepartment: "Yönetim Bilişim Sistemleri",
    kayitDate: "2025-09-01",
    status: "aktif",
    parent: "Mehmet Yılmaz",
    parentRelation: "baba",
    parentPhone: "532 555 66 77",
    email: "ayse.yilmaz@email.com",
    phone: "533 111 22 33",
    counselorName: "Ayşe Yılmaz",
    kullaniciAdi: "ayse.yilmaz",
    panelSifre: "Yks2026!",
    bursPercent: 15,
  },
  {
    ogrenciId: createOgrenciId(),
    coachId: DEFAULT_COACH_ID,
    name: "Can Demir",
    studentCode: "ÖĞ-CD002",
    sinifBranch: "12-B",
    alan: "sayisal",
    goal: "ODTÜ — Bilgisayar Mühendisliği",
    targetUniversity: "ODTÜ",
    targetDepartment: "Bilgisayar Mühendisliği",
    kayitDate: "2025-09-15",
    status: "aktif",
    parent: "Ali Demir",
    parentRelation: "baba",
    parentPhone: "533 444 22 11",
    kullaniciAdi: "can.demir",
    panelSifre: "Can2026#",
  },
  {
    ogrenciId: createOgrenciId(),
    coachId: DEFAULT_COACH_ID,
    name: "Zeynep Kaya",
    studentCode: "ÖĞ-ZK003",
    sinifBranch: "12-A",
    alan: "esit",
    goal: "Boğaziçi Üniversitesi — İşletme",
    targetUniversity: "Boğaziçi Üniversitesi",
    targetDepartment: "İşletme",
    kayitDate: "2025-10-01",
    status: "aktif",
    parent: "Fatma Kaya",
    parentRelation: "anne",
    parentPhone: "534 333 11 00",
  },
  {
    ogrenciId: createOgrenciId(),
    coachId: DEFAULT_COACH_ID,
    name: "Mert Öztürk",
    studentCode: "ÖĞ-MO004",
    sinifBranch: "11-F",
    alan: "sozel",
    goal: "İTÜ — Mimarlık",
    targetUniversity: "İTÜ",
    targetDepartment: "Mimarlık",
    kayitDate: "2025-11-01",
    status: "donduruldu",
    parent: "Hasan Öztürk",
    parentRelation: "baba",
    parentPhone: "535 222 33 44",
  },
  {
    ogrenciId: createOgrenciId(),
    coachId: DEFAULT_COACH_ID,
    name: "Burak Şahin",
    studentCode: "ÖĞ-BS005",
    sinifBranch: "Mezun",
    alan: "sayisal",
    goal: "Hacettepe Üniversitesi — Tıp",
    targetUniversity: "Hacettepe Üniversitesi",
    targetDepartment: "Tıp",
    kayitDate: "2024-06-01",
    status: "mezun",
    parent: "Emre Şahin",
    parentRelation: "baba",
    parentPhone: "537 999 88 77",
  },
];
