/** Serbest metinde stres / motivasyon / kaygı niyetini algılar */

const MENTAL_KEYS = [
  "motivasyon",
  "motivasyonum",
  "moralim",
  "moralsiz",
  "stres",
  "stresli",
  "kayg",
  "anksiyete",
  "panik",
  "bunald",
  "bunaldım",
  "bunaldim",
  "tükend",
  "tukend",
  "yoruld",
  "yoruldu",
  "bitkin",
  "umutsuz",
  "depres",
  "ağlad",
  "aglad",
  "ağlıy",
  "agliy",
  "pes et",
  "pes ed",
  "vazgeç",
  "vazgec",
  "yetişmeyecek",
  "yetismeyecek",
  "yapamıyorum",
  "yapamiyorum",
  "kötü his",
  "kotu his",
  "kendimi kötü",
  "kendimi kotu",
  "kendime güven",
  "kendime guven",
  "sıkıldım",
  "sikildim",
  "çalışasım yok",
  "calisasim yok",
  "odaklanam",
  "konsantre",
  "mental",
  "psikoloj",
  "kriz mod",
  "kendimi suçlu",
  "kendimi suclu",
  "felaket",
  "başarısız",
  "basarisiz",
  "yalnız his",
  "yalniz his",
];

export function isMentalIntentText(text: string): boolean {
  const t = text.toLocaleLowerCase("tr");
  if (!t.trim() || t.length < 4) return false;
  return MENTAL_KEYS.some((k) => t.includes(k));
}
